WIP: Using the FIP job Controller to query managed jobs
sighupio/fip-job-status-api pull request #11
Opened 2021-07-14 15:49 UTC by nandajavarma

2021-07-16 11:49 UTC, angelbarrera92 commented on deployments/kustomization/deployment.yaml
> +        image: nandajavarma/fip-job-status-api:latest
Be careful with this :)

2021-07-16 11:50 UTC, angelbarrera92 commented on internal/server/server.go
>  }
More simpler than before :) Looks good

2021-07-16 11:51 UTC, angelbarrera92 commented on pkg/checkresults/checkresults.go
> +)
I've added these constants to the fip-commons library if i recall correctly

2021-07-16 11:51 UTC, angelbarrera92 commented on pkg/checkresults/checkresults_test.go
> +// license that can be found in the LICENSE file.
If we don't add test here, consider removing this  file

2021-07-16 11:52 UTC, angelbarrera92 commented on scripts/e2e/tests.sh
> +        kubectl apply -f scripts/e2e/v1beta1.crd.yaml
Consider using a URL instead of copy-pasting the crd definition here

2021-07-16 11:53 UTC, angelbarrera92 commented on scripts/e2e/v1beta1.crd.yaml
> +# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
https://github.com/sighupio/fip-job-status-api/pull/11/files#r671184440

2021-07-16 11:53 UTC, angelbarrera92 requested changes
Minor comments. 

overall LGTM, but missing some clarifications

2021-07-16 12:47 UTC, nandajavarma commented on scripts/e2e/tests.sh
> +        kubectl apply -f scripts/e2e/v1beta1.crd.yaml
I will wait for the merge request to be merged for this

2021-07-16 12:54 UTC, nandajavarma commented on scripts/e2e/v1beta1.crd.yaml
> +# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
done

2021-07-19 10:42 UTC, angelbarrera92 commented on deployments/kustomization/rbac.yaml
>  - apiGroups: ["batch"]
Question here... Does this API needs `jobs` and `pods` permissions with this new approach?

2021-07-19 10:42 UTC, angelbarrera92 commented on examples/rendered.yaml
> +        imagePullPolicy: Always
be careful with this value for `imagePullPolicy`.

2021-07-19 10:58 UTC, nandajavarma commented on deployments/kustomization/rbac.yaml
>  - apiGroups: ["batch"]
ah you are right. It does not. I will change this!

2021-07-19 10:59 UTC, nandajavarma commented on deployments/kustomization/rbac.yaml
>  - apiGroups: ["batch"]
done!

2021-07-19 11:01 UTC, nandajavarma commented on examples/rendered.yaml
> +        imagePullPolicy: Always
with the unstable image, personally it makes more sense to me to use `Always`. If we were using a stable release, I would definitely stick to `IfNotPresent`.

2021-07-19 15:02 UTC, merged